//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0-SNAPSHOT.
//


package com.sinepulse.app.fragments;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.EditText;
import android.widget.ProgressBar;
import com.sinepulse.app.R.layout;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class UserProfileFragment_
    extends UserProfileFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.user_profile, container, false);
        }
        return contentView_;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static UserProfileFragment_.FragmentBuilder_ builder() {
        return new UserProfileFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        etSocialSecurity = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etSocialSecurity));
        etFirstName = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etFirstName));
        etEmail = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etEmail));
        etAddress2 = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etAddress2));
        etTelephone = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etTelephone));
        userProfileProgressBar = ((ProgressBar) hasViews.findViewById(com.sinepulse.app.R.id.userProfileProgressBar));
        etSex = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etSex));
        etCity = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etCity));
        etAddress = ((EditText) hasViews.findViewById(com.sinepulse.app.R.id.etAddress));
        afterViewLoaded();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public UserProfileFragment build() {
            UserProfileFragment_ fragment_ = new UserProfileFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
